### PR TITLE
Got it to run ShaderToy shaders, kind of.

### PR DESCRIPTION
**Pull request by odbol**
Simple ones work at least.

Added iResolution.

I will fix tabs/spaces soon, just wanted to get this out there see if I'm going in the right direction...

### CODE REVIEW

**Comment by ignlg** [comment]
+1 to this feature, it's really useful to be able to run shadertoy syntax files, like glslViewer (*nix) does.

**Comment by EternalClickbait** [comment]
@markusfisch Any updates on this? It's been a few years but a much needed feature.

**Comment by markusfisch** [comment]
Sorry for leaving this open for so long 🙈 I'll try to clean this up and merge it manually.

**Comment by markusfisch** [comment]
Version 2.23.3 tries to convert ShaderToy sources automatically now. It's currently in beta and should become available soon.

However, I chose a different approach and convert the ShaderToy symbols in the source instead of adding the corresponding uniforms. This way, the conversion is transparent and can be understood by the user.

For details see:
https://github.com/markusfisch/ShaderEditor/commit/2881b2a1a25236eb7c1c4df1ae28c994da35e4b4

**Pull request closed without merging**
