### PR TITLE
Add notification uniforms

### LINKED ISSUE #136: Features request: Notification detector
I guest if this feature appear on this apps, more interactive shader will be amazing

### PR DESCRIPTION
**Pull request by AntonPieper**
This adds the `notificationCount` and `lastNotificationTime` uniforms using a `NotificationListenerService`. The user gets asked for the permission every time he opens a shader using these uniforms if he has not yet accepted the permission.

Closes #136

### CODE REVIEW

**Comment by markusfisch** [comment]
Great work! Thanks a lot! 👍

**Comment by zedpoirier** [comment]
Amazing! 

Forgive the basic question, but will this push go out to the play store soon or would I need to wait for a new release here on github, or build it myself? (Im not really rushed, just curious).

**Comment by markusfisch** [comment]
@zedpoirier I'll do a release very shortly! I just want to run a few test and because I'm quite busy at work, it's a bit challenging to allocate the time, unfortunately. But I will do a release this week!

If you want to try that feature earlier, and possibly give feedback on it before a release (which I would greatly appreciate), you would need to build the app yourself indeed. It would be installed as a debug version that won't collide with the official release so you won't break anything with it.

**Comment by zedpoirier** [comment]
I would love to help out and build it myself. It has been a long while since I did any Android dev, do you have any resources you can share for getting a build environment up and running for this project?

**Comment by markusfisch** [comment]
Yes, building the app should really be easy these days:

1. Just install [Android Studio](https://developer.android.com/studio)
2. Get the project via "File" -> "New" -> "Project from Version Control…"
3. Enter the address of this repository: `https://github.com/markusfisch/ShaderEditor.git`
4. Then "Run" -> "Run app" or just hit the little green play button in the toolbar

If you want to see this in action, just check these videos on [YouTube](https://www.google.com/search?q=youtube+android+studio+clone+project) 😉 

But since I already released [Version 2.33.3](https://github.com/markusfisch/ShaderEditor/releases/tag/2.33.3) in the meantime, you can also just update from Google Play now.

**Comment by zedpoirier** [comment]
Oh awesome! I did happen to get a build working to and functionally it seems to be working! Now there is a small issue (this may be my device specific tho):

I did a quick test by just using the default shader and inverting the colors if I have notifications. But even though it appears to me that I currently have ZERO notifications, the notificationCount was returning a value of greater than Zero. I imagine this might be related to some kind of hidden notifications and definitely something I can work around, but just thought that was worth sharing.

Thank you so much for adding this in! :)

**Pull request merged**
