### PR TITLE
Add smart auto-completions

### LINKED ISSUE #175: Suggestion: Add typing-relevant bar above keyboard
I thought, maybe adding a bar above the keyboard for some actions (like auto complete) could be useful. The thing is, I also like simplicity and a simple user interface. So I am asking if this is a wanted feature?

Here is a quick sketch (of course this is not the design I would implement)
Screenshot_20240417-172914

### PR DESCRIPTION
**Pull request by AntonPieper**
This implements smart auto completions when writing code.

There are still some points that need to be fixed:

- [x] Fix updating of completions
  - [x] Faster completions -> Lexing instantly ~(and implement incremental updates?)~
  - [x] Fix crash (could not yet replicate again)
  - [x] Show completions when writing text
- [x] Only use the part of the token up to the cursor position for the prefix search
- [x] Replace the token up to the cursor instead of inserting the text

Closes #175

### CODE REVIEW

**Comment by AntonPieper** [comment]
I actually discovered a bug, but can't edit this again to mark as a draft.

Loading a different shader does not update highlighting and creating a new one crashes the app.

I think the problem is that that [`setText`](https://github.com/AntonPieper/ShaderEditor/blob/6eda6020f117bf0900e87a260228f63116298790/app/src/main/java/de/markusfisch/android/shadereditor/widget/ShaderEditor.java#L192) does not trigger the Text watcher but I'll have to look into that.

**Comment by markusfisch** [comment]
Okay, no problem, I'll wait until you say it's ready then.

I'll probably do an intermediate release before merging this anyway, mainly because of the `PagerTabStrip` bug you found yesterday.

**Comment by AntonPieper** [comment]
I was right with my guess, it is now fixed and ready for review / merge

**Comment by AntonPieper** [comment]
Also with this feature added, it might make sense to update the ReadMe and PlayStore page with updated images and descriptions to show the current visuals

**Comment by markusfisch** [comment]
Merged, and already on it's way through Google Play 😉 I also updated the screenshots to show the latest UI changes. The new version is [2.34.0](https://github.com/markusfisch/ShaderEditor/releases/tag/2.34.0).

Once more, thank you very much for all the work you put into this! Highly appreciated!

**Pull request merged**
