### PR TITLE
Extra keys

### PR DESCRIPTION
**Pull request by AntonPieper**
This adds an extra row above your keyboard for quick actions like inserting a tab or auto-completion a relevant for writing your shader. This also removes the regular Auto-Suggestion bar from your keyboard.

<details>
<summary>Current State (screenshot)</summary>

This is what it currently looks like. I want to integrate auto-completion based on the cursor position (instead of a static list). The buttons still need some fixing and maybe the design could be improved a bit.
Screenshot_20240505-155309

</details>

### CODE REVIEW

**Comment by markusfisch** [comment]
This looks great! 👍 I really like it! 😄  And yes, context sensitive auto-completion would be nice, but I don't think it is strictly necessary to release this. The extra bar makes editing already easier as it is right now, and we can always update and expand this.

One small thing I would like to add is to show and hide the extra bar with the soft keyboard. Which isn't all that trivial because there's no API to listen for keyboard visibility changes, unfortunately. But apparently, we can use an `OnGlobalLayoutListener` to [detect keyboard visibility changes](https://stackoverflow.com/questions/4745988/how-do-i-detect-if-software-keyboard-is-visible-on-android-device-or-not), which I would like to try.

Is there anything missing for a merge? As far as I see the feature is complete and working 🤔

**Comment by AntonPieper** [comment]
Functionality-wise, it is working👍 Although I would like to try a different design, where there are Text-Buttons and some dividers between them as seen in the menu. Also I want to find the cause for the padding around the buttons and patch `insertTab` to just use the new `insert` method

**Comment by AntonPieper** [comment]
> One small thing I would like to add is to show and hide the extra bar with the soft keyboard. 

This is something that could be integrated as well👍 One scenario I can think of though is that if dynamic auto completion is implemented, it could be useful even for physical keyboard users on tablets to see the suggestions on a bar at the bottom of the screen, as seen on iPads. So maybe it could be a toggle in the settings or menu?
image
(ironically, this image is from a guide on [how to disable it](https://wccftech.com/how-to/disable-this-feature-on-your-ipad-to-turn-it-into-a-proper-laptop/))

**Comment by markusfisch** [comment]
> Although I would like to try a different design, where there are Text-Buttons and some dividers between them as seen in the menu. Also I want to find the cause for the padding around the buttons and patch insertTab to just use the new insert method

Ah, I see, okay then I'll wait until then. Patching `insertTab` to also use the new `insert` method definitely makes sense 👍 

> One scenario I can think of though is that if dynamic auto completion is implemented, it could be useful even for physical keyboard users on tablets to see the suggestions on a bar at the bottom of the screen, as seen on iPads. So maybe it could be a toggle in the settings or menu?

Yes, absolutely! A setting would probably be the best option. I can imagine some people prefer it to be permantenly visible, especially on very big screens like you mentioned.

**Comment by AntonPieper** [comment]
Now I have changed the design a bit, this is what it look like now:
<details>
<summary>Screenshot</summary>

Screenshot_20240509-124459
</details>

I am still not quite sure how I could elegantly signal to the user that they can actually scroll through these options. Maybe it is enough to rearrange the options, so that on most screens, the last option is not fully on the screen? Also, what options should be there in general?

**Comment by markusfisch** [comment]
> Now I have changed the design a bit, this is what it look like now:

I like that! 👍 

> I am still not quite sure how I could elegantly signal to the user that they can actually scroll through these options. Maybe it is enough to rearrange the options, so that on most screens, the last option is not fully on the screen?

With Android's countless screen sizes it probably doesn't make too much sense to try to arrange the buttons so that the last one is exactly on the edge. I would actually just leave it as it is, or perhaps add a small icon (for example “...”) at the end. Sometimes, an alpha gradient is used for the last item to indicate that there is more. But I'm not sure if it's worth it.

> Also, what options should be there in general?

Good question. How about trying to complete (key)words if there are letters on the left of the cursor? So if I type "ve" the bar could contain "`vec3`|`vec4`|…".

When we're at the start of a line, the bar could just offer the most common control statements like `if`|`for`|`while` but maybe also "`float`|`int`|`vec2`|…".

**Comment by markusfisch** [comment]
Yes, agreed! This is a great step forward already! Thank you for your awesome work on this! 👍 

>  I think, I can implement it by using a combination of bucketing and a binary search for the closest token and then using the Trie to provide the autocmpletion results.

Sounds good! 🤔

**Pull request merged**
