### PR TITLE
Added texture input from bitmap,  and saveShader in onPause.

### PR DESCRIPTION
**Pull request by svenhenrik**
Hi, I wanted to experiment with iq's bitmap-derived noise from shadertoy.com, so I added texture input. 

It's not really ready to just include as It currently reads from a hard coded path on the sd card and dies spectacularly if the file is missing. I also added a call to saveShader in MainActivity.onPause() because I kept losing my work after rotating or pressing the back button.

Feel free to use or ignore, thought I should at least share it with you :)

Oh, I should note that I haven't been able to get the noise working without artifacts, not sure why.

### CODE REVIEW

**Comment by markusfisch** [comment]
Hi, very cool! I've been planing to implement this for some time now so this comes in really handy. Thanks a lot for sharing!

Because of the hard wired file I won't directly merge it in but build a release version on top of this.

**Comment by svenhenrik** [comment]
Yeah, no problem! I think the saveShader call is causing a bug though, I'm getting some duplicate shaders in my saves. I didn't really use the build much before adding it so I'm not 100% it's because of that, but it sounds likely.

I still haven't been able to get the noise working though, I've replicated the glTexImage2d call from the shadertoy sources but the darn noise still wont be smooth. Still, should be useful for just adding a texture.

A thought might be to add texture_repeat, texture_mirror_repeat etc with different texture parameters.

**Comment by svenhenrik** [comment]
Hmm, actually just managed to get the noise working by generating my own noise texture instead of using the texture from shadertoy.com. Not sure if you're interested in the noise at all, but I'll push it to a new branch so you can have a look if you want to :)

**Comment by svenhenrik** [comment]
Noise works if I generate my own noise texture instead of using the PNG from shadertoy. Not sure if you're at all interested in the noise but I'll put on a branch in my fork and you can have a look if you feel like it :)

**Comment by markusfisch** [comment]
That's fine! Noise is quite important. So I really appreciate your work and hope to implement it very soon in the master branch.

Currently I'm trying to switch to the new support preference library which goes not as smooth as I thought. But right after that, I'll add support for textures.

About the bug with saveShader() in onPause(); I think I need to change saveShader() in order to work in onPause(). Now, saveShader() requests a thumbnail from the running shader which is blocking onPause() what's bad. Although having duplicates probably means there's something wrong with the id argument.

**Comment by Frez-M** [comment]
i think it could be also cool, when the app precaches (prerenders) some blurred textures of imported texture or you choose to prerender or not (to save some memory) (just sayin', i got some cool idea about them)

**Comment by markusfisch** [comment]
Partly (and manually) merged into master.

**Pull request closed without merging**
