### PR TITLE
Add popular fonts and ligatures

### LINKED ISSUE #126: Monospace whitespaces in editor
Currently there are some whitespaces (specifically spaces) that aren't the same width. This messes up the indenting a lot of times.
It would be nice to have a monospaced font with only one space width.

### PR DESCRIPTION
**Pull request by AntonPieper**
Uses JetBrains Mono by default, this can be changed at [preference_font.xml#L17](https://github.com/AntonPieper/ShaderEditor/blob/415b1c01a503f6b1841c506cb46716643808546f/app/src/main/res/values/preference_font.xml#L17).

You can change the font and whether you want to use ligatures in the Settings.

This should close #126

### CODE REVIEW

**Comment by markusfisch** [comment]
This is crashing for me with an `IllegalArgumentException` 😬 
```
Caused by: java.lang.IllegalArgumentException: font "null" not found!
    at de.markusfisch.android.shadereditor.preference.Preferences.getLoadedFont(Preferences.java:148)
```

**Comment by AntonPieper** [comment]
Hmm, that's weird, it worked on my machine™... I guess the preference sets a wrong value, (none was set at all?) or the function got called before the initialization function?

**Comment by AntonPieper** [comment]
I had assumed that passing `null` to `getString` would load the specified `defaultValue` from the XML, but I was wrong _(should have read the documentation)_. It worked on my machine because I had already opened the preferences before implementing the font handling logic.

**Comment by markusfisch** [comment]
I had suspected something like this but hadn't the time to dig deeper yesterday.

**Pull request merged**
